### ISSUE TITLE
Prompt to save changes of the the first default blank file created on each startup of rnote

### ISSUE THREAD

**Issue by wl0t** [flxzt/rnote#1258]
**Describe the bug**  
A prompt to save file or ignore modifications appears when trying to close the default empty and unmodified document that is created at startup of rnote.

The first empty document created at start-up should be considered as empty and unmodified by default. (as it is the case for other empty document created when opening new tabs).

**To Reproduce 1**  
1.Start rnote
2.Try to close rnote
3.A popup appears prompting to save the modifications or ignore modifications of the empty document.

Or equivalently:

**To Reproduce 2**  
1.Start rnote.
2. Create a new empty document in a new tab. 
3. Try to close the first empty document of the initial tab.
3.A popup appears prompting to save the modifications or ignore modifications of the empty document.

**Expected behavior**  
This prompt should not appear as the document is empty and unmodified.

**Desktop (please complete the following information):**  
 - OS: Fedroa 40
 - App Version: Rnote v0.11.0]
 - Installation Source: Flatpak

**Comment by florent0001** [comment]
I also observe the same behavior on v0.11.0 on windows 11. Draw with touch is off on both OS. I also observe the bug with only a mousse as an input (so it seems unlikely there is an unwanted stroke ?)

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Doublonmousse** [comment]
I think I have an idea. Maybe this has to do with how settings are loaded on startup. 

So everything that's part of the document but is displayed in the side panel (page format and document). Maybe the canvas loads first but the ui gets updated later, triggering a fictitious change.

**Comment by twoexem** [comment]
I have this issue too. Not the worst thing in the world but it's slightly annoying to close the dialogue everytime I close the document.

**Comment by Doublonmousse** [comment]
I've created a branch that prints how the unsaved indicator activates and I'm compiling it as a flatpak nightly here: https://github.com/Doublonmousse/rnote/actions/runs/14339727330 so that you can install this version and report what the terminal output looks like.

The guide to install flatpak nightlies is here : https://github.com/flxzt/rnote/blob/6c62026cb587f6d02c6064ec711a4d6abd0fc542/BUILDING.md#nightlies

**Comment by twoexem** [comment]
Sadly the flatpak doesn't seem to have the issue anymore. It doesn't create an empty but marked as modified tab.

**Comment by Doublonmousse** [comment]
> Sadly the flatpak doesn't seem to have the issue anymore. It doesn't create an empty but marked as modified tab.

Sorry I don't really understand.
Is the flatpak 0.12 version fixed ?

Are you talking about the modified flatpak nightly from here (that would mean this debug version works ?) ? https://github.com/Doublonmousse/rnote/actions/runs/14339727330

If you are running the nightly flatpak from the link and it exhibits the issue, can you please copy what's displayed in the terminal output ?

**Comment by twoexem** [comment]
I'm talking about the modified flatpak, yes. It doesn't exhibit the issue, however my main Rnote installation (Arch Linux binary installed via Pacman, 0.12) still has the problem.

**Comment by Doublonmousse** [comment]
Okay, so I've pulled https://gitlab.archlinux.org/archlinux/packaging/packages/rnote and made a custom version here https://github.com/Doublonmousse/rnote_aur_debug so that (hopefully) this custom version can be installed and repro the issue with the debug prints

**Comment by twoexem** [comment]
Cheers, that worked. Now it sets the unread flag upon lanch. Here's the relevant output:

<details>
<summary>Output of the modified debug package upon launch</summary>
setting unsaved indicator to true from "handle_widget_flags : WidgetFlags { redraw: true, resize: false, refresh_ui: false, store_modified: true, view_modified: false, zoomed_temporarily: false, zoomed: false, deselect_color_setters: false, hide_undo: None, hide_redo: None, enable_text_preprocessing: None, origin: \"imp.doc_background_pattern_width_unitentry.get().connect_notify_local\" }"
setting unsaved indicator to true from "handle_widget_flags : WidgetFlags { redraw: true, resize: false, refresh_ui: false, store_modified: true, view_modified: false, zoomed_temporarily: false, zoomed: false, deselect_color_setters: false, hide_undo: None, hide_redo: None, enable_text_preprocessing: None, origin: \"imp.doc_background_pattern_width_unitentry.get().connect_notify_local\" }"
setting unsaved indicator to true from "handle_widget_flags : WidgetFlags { redraw: true, resize: false, refresh_ui: false, store_modified: true, view_modified: false, zoomed_temporarily: false, zoomed: false, deselect_color_setters: false, hide_undo: None, hide_redo: None, enable_text_preprocessing: None, origin: \"imp.doc_background_pattern_height_unitentry.get().connect_notify_local\" }"
setting unsaved indicator to true from "handle_widget_flags : WidgetFlags { redraw: true, resize: false, refresh_ui: false, store_modified: true, view_modified: false, zoomed_temporarily: false, zoomed: false, deselect_color_setters: false, hide_undo: None, hide_redo: None, enable_text_preprocessing: None, origin: \"imp.doc_background_pattern_height_unitentry.get().connect_notify_local\" }"
</details>

**Comment by Doublonmousse** [comment]
Thanks you, that helps a lot (it also means it'll be possible to test a patch) !

**Comment by twoexem** [comment]
Cheers, no problem!

By the way, I finally fixed that darn Markdown after fighting with it for 5 minutes.

**Comment by Doublonmousse** [comment]
I've pushed a new version with a (what I think) is a fix https://github.com/Doublonmousse/rnote_aur_debug 

It's maybe not the full complete thing (maybe elements other than `doc_background_pattern_width_unitentry`/doc_background_pattern_height_unitentry` can trigger this but these ones shouldn't appear now and extending to the rest won't be difficult).

And for good measure (if other can reproduce the issue on the flatpak, a fixed version/nightly here : https://github.com/Doublonmousse/rnote/actions/runs/14926012771)

**Comment by twoexem** [comment]
Sadly this doesn't solve the issue for me, here's my log output:

<details>
<summary>Log output</summary>

```
setting unsaved indicator to true from "handle_widget_flags : WidgetFlags { redraw: true, resize: false, refresh_ui: false, store_modified: true, view_modified: false, zoomed_temporarily: false, zoomed: false, deselect_color_setters: false, hide_undo: None, hide_redo: None, enable_text_preprocessing: None, origin: \"imp.doc_background_pattern_width_unitentry.get().connect_notify_local\" }"
setting unsaved indicator to true from "handle_widget_flags : WidgetFlags { redraw: true, resize: false, refresh_ui: false, store_modified: true, view_modified: false, zoomed_temporarily: false, zoomed: false, deselect_color_setters: false, hide_undo: None, hide_redo: None, enable_text_preprocessing: None, origin: \"imp.doc_background_pattern_width_unitentry.get().connect_notify_local\" }"
setting unsaved indicator to true from "handle_widget_flags : WidgetFlags { redraw: true, resize: false, refresh_ui: false, store_modified: true, view_modified: false, zoomed_temporarily: false, zoomed: false, deselect_color_setters: false, hide_undo: None, hide_redo: None, enable_text_preprocessing: None, origin: \"imp.doc_background_pattern_height_unitentry.get().connect_notify_local\" }"
setting unsaved indicator to true from "handle_widget_flags : WidgetFlags { redraw: true, resize: false, refresh_ui: false, store_modified: true, view_modified: false, zoomed_temporarily: false, zoomed: false, deselect_color_setters: false, hide_undo: None, hide_redo: None, enable_text_preprocessing: None, origin: \"imp.doc_background_pattern_height_unitentry.get().connect_notify_local\" }"
```
</details>

**Comment by twoexem** [comment]
Suddenly the issue is fixed in my main Rnote installation (pacman reports it as version 0.12.0-2). I can't remember updating my system before, so this may have occured due to me installing the development version, which prompted a reinstallation of the main package, however, the bug does persist in the _development_ version. No clue what's going on here. Did the debug package accidentally end up as my main package?

**Comment by twoexem** [comment]
Here's the log output of my currently functional main install:
<details>
<summary>Log output</summary>
```init function
init
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
refresh ui from engine from setup_tabview
refresh ui from engine with init true
refresh doc ui with init value true
set signal state to false
handler id exists applying
handler id exists applying
set signal state to true
handler id exists applying
handler id exists applying
refreshing ui from engine (init)
refresh ui from engine with init true
refresh doc ui with init value true
set signal state to false
handler id exists applying
handler id exists applying
set signal state to true
handler id exists applying
handler id exists applying

```
</details>

**Comment by Doublonmousse** [comment]
So yes that's the new dev version.

That means the fix works (I'll try to push a full and cleaner version soon to the main branch)

Sorry If I made a mess of your install !

**Comment by twoexem** [comment]
@Doublonmousse Any progress on the fix?

**Comment by Doublonmousse** [comment]
@twoexem I've found another way to do this that's much less painful and updated the PR in consequence.

I have the bug on my windows machine (on 0.12) and it fixes it on this one.
Do you want me to repackage like last time so that you can double check on your side if this seems to fix it ?

**Comment by twoexem** [comment]
Sure, that'd be nice. Thanks!

**Comment by Doublonmousse** [comment]
@twoexem Alright I've updated https://github.com/Doublonmousse/rnote_aur_debug to use the PR branch.

This time the version will register as 0.13 (the version bump comes from an unrelated recent file format change) so it'll be easier to verify which version is the dev one

**Comment by twoexem** [comment]
Hi, I believe the PKGBUILD is faulty. When trying to compile the package, I get the error ERROR: rnote-fix_1258_unsaved_upon_startup.tar.gz is not a directory.

**Comment by twoexem** [comment]
After fixing the PKGBUILD error, I was able to compile the package. The error is gone in that version. Something peculiar I noticed: When installing these development packages, they seem to replace the original Rnote executable with their own. Had to remove both rnote and rnote-debug and install rnote again to get 1.12 to display when executing rnote.

**Comment by Doublonmousse** [comment]
1.12 ? Not 0.13 ??

If it works that's kinda all of the info I need, thanks for testing !

The packaging might not work well for this but as I'm not actually trying to maintain a package out of this it's fine I guess

**Comment by twoexem** [comment]
@Doublonmousse Any news on implementing this fix?

**Comment by Doublonmousse** [comment]
Well, the current fix wasn't merged (in part because it is probably preventing the actual bug from applying changes, not fixing the root cause itself, and it's in consequence a little weird as far as code goes because we do more than we should for code that otherwise should work).

As I was looking over again, I think it's no coincidence that you get 
```
imp.doc_background_pattern_width_unitentry.get().connect_notify_local
``` 
And the height equivalent twice and switching around two lines of code should fix that. I'm going to try this again with this fix instead and see if this is all there is to it. If so, it'll be a much more proper fix that can actually get merged
