### ISSUE TITLE
Primary stylus button breaks after using secondary button

### ISSUE THREAD

**Issue by Acumane** [flxzt/rnote#705]
**Describe the bug**  

Using the secondary stylus button (selector mode) breaks the primary button, which persists between sessions—though using "Selector" via toolbar works as you'd expect.
All stock settings; changing "Button Shortcuts" have no effect. Only resets when uninstalled & remaining files wiped from `~/.var/app`

**To Reproduce**  
1. Press and hold secondary stylus button (selector mode)
2. Select something (?)
3. Release
4. Primary button (erase) now has no effect

**Console Output**
Sparse. Just after copying a selection:
```
2023-06-11T03:15:41.466Z DEBUG rnote::appwindow::appwindowactions > recognized clipboard content format: application/rnote-stroke-content
```

**Desktop**  
 - OS: Fedora 38
 - App Version: 0.6.0 
 - Installation Source: Flatpak

**Comment by PeterWang-dev** [comment]
same thing happening on windows

**Comment by Acumane** [comment]
I'd tentatively say this was fixed in `v0.8.2`... I'll keep testing

**Comment by GabriF** [comment]
Just had same problem, but can't fix it. I don't have any ~/.var and uninstalling didn't solve it.
