### ISSUE TITLE
Window does not resize on mac and has no decoration

### ISSUE THREAD

**Issue by DorianRudolph** [flxzt/rnote#823]
**Describe the bug**  

**To Reproduce**  

**Expected behavior**  

**Console Output**  
Run the app in the terminal with `flatpak --env=RUST_LOG=rnote=debug --env=RUST_BACKTRACE=1 run com.github.flxzt.rnote` and post the output.

**Screenshots**  

**Desktop (please complete the following information):**  
 - OS: [e.g. Fedora 38,  Windows 11 22H2, ...]
 - App Version: [e.g. Rnote v0.9.0]
 - Installation Source: [e.g. Flatpak, Archlinux Community Repo, ...]
 - Desktop Environment: [e.g. Gnome 44.2]

**Additional context**

**Comment by dehesselle** [comment]
Before updating to Sonoma, have you been using Rnote on Ventura without this issue?

**Comment by DorianRudolph** [comment]
Apple Silicon (M1 Max). I'm not sure if it worked before the update. I think it did, but I'm not very certain.

**Comment by dehesselle** [comment]
Wait a second, what do you mean "has no window decoration"? The decoration is right there. It's just not native macOS as Rnote uses a multiplatform UI framework that has its own distinctive look.

I cannot reproduce any issue on my test machine which runs Sonoma beta 3 (updating to release version right now). It is an Intel machine though, I do not have a Apple Silicon machine running Sonoma.

**Comment by dehesselle** [comment]
I can't reproduce any issue on the stable version of Sonoma either. Can you record a video of your resizing problem?

**Comment by DorianRudolph** [comment]
Sorry, but after a reboot, I can't reproduce the issue anymore. With "no window decoration" I meant the missing shadow and square corners. It seems on my screenshot, rnote got stuck in a maximized mode and could not be resized anymore. Another thing I noticed was that rnote could be resized by rectangle after the reboot, but not after playing around (moving, resizing, adding and removing monitors) for a bit. If I encounter the issue again, I will record a video.

**Comment by Doublonmousse** [comment]
I can reproduce the issue on a M2 mac mini with the latest os and rnote 0.9. I could not resize the rnote window at any point.

I started with a rnote window that was taking the full screen but was not resizable and ended up with a window that was smaller than the fullscreen size and still not resizable by any means.
Do you have betterdisplay installed ? I have a "non-apple" resolution of 1440p and use betterdisplay to get around the terrible scaling of mac os, and playing with resolutions/scaling made it broke even more.

**Comment by LeSnake04** [comment]
Can confirm this on my work macbook (m1). Has been like that since I think 7.1.

(Since it isnt my personal laptop, I am limited in testing of hotfixes thoug)

**Comment by dehesselle** [comment]
If you disconnect the external monitor and open Rnote using the internal display only, does the issue persist?

**Comment by DorianRudolph** [comment]
I don't have BetterDisplay. I occasionally use EasyRes to change the resolution, but I usually don't run nonstandard resolutions. I think a GTK4 bug sounds pretty likely.

**Comment by dehesselle** [comment]
The issue above mentions [Gaphor](https://gaphor.org) as another GTK4 program to test, but the OP never responded to that. Can someone who is facing this issue give that a spin?
Another candidate would be [Zrythm](https://www.zrythm.org). Or any other GTK4 based program that is being built for macOS - let me know if you are aware of any other apps.

**Comment by Doublonmousse** [comment]
For Gaphor
- resizing works, maximizing as well, even if the animation is a little weird. 
- interaction with Rectangle does not work
- interaction with alt-tab (another utility to alt-drag windows around) does work, but not for resizing

What I could not find is the specific version of gtk/libadwaita used in the `brew` package (the repository only list minimum version requirements, maybe we have to look at the brew formula to find it ?).

I'll try zrythm next

**Comment by Doublonmousse** [comment]
Well I can't get zrythm to launch at all at without it crashing on launch...

**Comment by dehesselle** [comment]
I'll build `gtk4-demo` so we can confirm if it's a general issue or not.

**Comment by flxzt** [comment]
It might be worth to test the adwaita demo as well - because of its new `BreakPoint` API and the adaptive widgets.

**Comment by LeSnake04** [comment]
> If you disconnect the external monitor and open Rnote using the internal display only, does the issue persist?

when I open Rnote without a external display, it becomes fullscreen but I cant rezize it.

**Comment by LeSnake04** [comment]
@flxzt does rnote try to maximize/modify the window? [this comment](https://gitlab.gnome.org/GNOME/gtk/-/issues/5898#note_1850299) says not maximizing via the built in function fixed it for them.

**Comment by flxzt** [comment]
rnote restores the saved window dimensions and the maximized state from the last session - see [here](https://github.com/flxzt/rnote/blob/2bbdcc267d0a87c2724134763c31a83d847de3e2/crates/rnote-ui/src/appwindow/appsettings.rs#L391). And it of course maximizes the window when the maximize button is clicked

**Comment by LeSnake04** [comment]
So a build without restoring dimensions and maximized state might fix the issue.

**Comment by dehesselle** [comment]
I've created artifacts that contain the demo programs for testing purposes. You need to [download them directly from CI](https://gitlab.com/dehesselle/rnote_macos/-/pipelines/1052652898/builds).

1. Drag the application from the dmg to your desktop, not to the applications folder (so you don't overwrite your existing app).
2. Open the terminal.
3. Remove quarantine flag.
   ```bash
   xattr -r -d com.apple.quarantine $HOME/Desktop/Rnote.app
   ```
4. Set environment variables.
   ```bash
   RNOTE_APP=$HOME/Desktop/Rnote.app
   DYLD_LIBRARY_PATH=$RNOTE_APP/Contents/Resources/lib:$RNOTE_APP/Contents/Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders
   GDK_PIXBUF_MODULE_FILE=$RNOTE_APP/Contents/Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
   XDG_DATA_DIRS=$RNOTE_APP/Contents/Resources/share
   export DYLD_LIBRARY_PATH GDK_PIXBUF_MODULE_FILE XDG_DATA_DIRS
   ```
5. Run either
   ```bash
   # If you want to run the GTK demo program:
   $RNOTE_APP/Contents/Resources/bin/gtk4-demo
   ```
   or
   ```bash
   # If you want to run the libadwaita demo program:
   $RNOTE_APP/Contents/Resources/bin/adwaita-1-demo
   ```

**Comment by Doublonmousse** [comment]
Well, testing the artifacts (`gtk4-demo` and `adwaita-1-demo`) I did not encounter any issues, even when switching between resolutions and fullscreen/not fullscreen mode using better display.

Even if I reinstall rnote (remove the rnote app then putting it back again), my rnote window is still the wrong size and will not be able to be maximized (and it is the same wrong size everytime). Is there some cache file I should delete to have a 'clean' reinstall or some resolution info from the last session used to launch rnote again ?

**Comment by Doublonmousse** [comment]
I think I have found the bug.

First how to make the bug appear :
- open rnote
- maximize
- open betterdisplay and lower the resolution
- maximize rnote
- open betterdisplay and increase the resolution
- close the rnote window

Then for each subsequent launch of rnote, the size of the window will be fixed and no resizing or maximizing can be done.

Removing the plist file then restarting mac os (seems that the last configuration is loaded even if the plist file is deleted !) resets the defaults parameters and rnote will then work as expected.

What I've found is that on the incorrect plist, the maximize state is set to true, but the resolution given in the plist is also respected to the letter, even if the resolution listed does not correspond at all with the resolution rnote would have to be maximized. Thus, rnote thinks it is maximized so resizing is disabled but mac os thinks otherwise...

We could try
- if `is-maximized` is true, maximize the window but do NOT restore the width/height in the file
- if `is-maximized` is false, restore the default width/height

P.S. : I haven't found a good way to edit the plist file directly and reliably to test every settings but this seems like a good start.

**Comment by flxzt** [comment]
okay, I pushed a possible fix. Can youcreate another macos build so it can be tested @dehesselle  ?

**Comment by dehesselle** [comment]
Artifacts are ready: https://gitlab.com/dehesselle/rnote_macos/-/pipelines/1054036648/builds

**Comment by Doublonmousse** [comment]
Well, it does not seem to fix the issue on my side.
So using the `maximize` command is probably causing the bug.

**Comment by flxzt** [comment]
Should the app just not restore the maximized state on macos for now, until this bug is fixed in gtk?

**Comment by dehesselle** [comment]
Artifacts for `v0.9.0-24-g0aef3ca2`:
https://gitlab.com/dehesselle/rnote_macos/-/pipelines/1056092811/builds

**Comment by Doublonmousse** [comment]
This works on my side now. 
Well it's a shame the first attempt did not work but it was worth trying at least.

Putting the gtk issue link again so we don't have to search for it too much : https://gitlab.gnome.org/GNOME/gtk/-/issues/5898

**Comment by Doublonmousse** [comment]
One of the main contributor from the `gaphor` project implemented in gaphor a way to restore the maximize status of the window (not on the start window but on the main window for editing a diagram), and I can test and confirm it works, whilst doing the same in `rnote` (forcing a maximize to take place, with or without setting first the default window size) doesn't on the same gtk version.

What is done in gaphor is using python but the logic is the same : https://github.com/gaphor/gaphor/pull/2896/files#diff-e457c14223121ea6acd302856d8886fbfc7ab569bab9ae9f1cffccc2b2ec51bd

So I'm wondering if this is somehow a bug in the wrapper, where the python one is correctly working but the rust one (`gtk-rs`) isn't on the maximize command.

**Comment by Doublonmousse** [comment]
I found on that doing this 
```rs
appwindow.present()
appwindow.maximize(); // maximize the window AFTER presenting it
```
will not trigger the bug. 
Somehow calling `present` before `maximize` on the window prevents the bug on rust but not on pygobject ... I updated the issue on the gtk tracker as well.

**Comment by Doublonmousse** [comment]
Should be fixed in the next stable gtk release (4.14)

**Comment by Doublonmousse** [comment]
Fully fixed with 0.11
